version: 2
updates:
  # Monitor GitHub Actions for dependency updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Nexus-Security"
